version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: de_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - de_lake_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # This container simply creates the bucket 'data-lake' on startup
  minio-create-bucket:
    image: minio/mc:latest
    container_name: de_minio_init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin && /usr/bin/mc mb myminio/data-lake --ignore-existing && /usr/bin/mc anonymous set download myminio/data-lake "
    networks:
      - de_lake_net

networks:
  de_lake_net:
    driver: bridge

volumes:
  minio_data:
